# mascots_util.py
# Robust mascot + logo lookup with recursive search and team_logos.json support.

from __future__ import annotations
import os, re, unicodedata, json
from typing import Optional
from pathlib import Path

def _norm(s: str) -> str:
    s = unicodedata.normalize("NFKC", (s or "")).strip().lower()
    return re.sub(r"\s+", " ", s)

def _alnum(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", _norm(s))

# ---------- load mascots ----------
MASCOTS_RAW, LOGOS_RAW = {}, {}

# Prefer Python dicts in team_mascots.py
try:
    import team_mascots as TM
    if hasattr(TM, "team_mascots") and isinstance(TM.team_mascots, dict):
        MASCOTS_RAW = dict(TM.team_mascots)
    if hasattr(TM, "team_logos") and isinstance(TM.team_logos, dict):
        LOGOS_RAW = dict(TM.team_logos)
except Exception:
    pass

# Optional JSON fallbacks
if not MASCOTS_RAW and Path("team_mascots.json").is_file():
    try:
        MASCOTS_RAW = json.loads(Path("team_mascots.json").read_text(encoding="utf-8"))
    except Exception:
        MASCOTS_RAW = {}

# NEW: auto-read team_logos.json generated by generate_logos.py
if Path("team_logos.json").is_file():
    try:
        from_json = json.loads(Path("team_logos.json").read_text(encoding="utf-8"))
        if isinstance(from_json, dict):
            # JSON takes precedence over auto-discovery, but not over explicit python paths
            for k, v in from_json.items():
                LOGOS_RAW.setdefault(k, v)
    except Exception:
        pass

# ---------- build mascot indices ----------
_MASCOTS_BY_NORM: dict[str,str] = {}
_MASCOTS_BY_ALNUM: dict[str,str] = {}
for k, v in (MASCOTS_RAW or {}).items():
    _MASCOTS_BY_NORM[_norm(k)] = v
    _MASCOTS_BY_ALNUM[_alnum(k)] = v

# ---------- logo search ----------
_REPO_ROOT = Path(__file__).resolve().parent

_CANDIDATE_DIRS = [
    _REPO_ROOT / "assets" / "logos",
    _REPO_ROOT / "assets" / "Logos",
    _REPO_ROOT / "logos",
    _REPO_ROOT / "logos" / "generated_logo",   # your generated set
    _REPO_ROOT / "logos" / "ai",              # your AI-generated set
    _REPO_ROOT / "static" / "logos",
    _REPO_ROOT / "images" / "logos",
]

def _iter_logo_files():
    exts = (".png", ".jpg", ".jpeg", ".gif")
    for base in _CANDIDATE_DIRS:
        if not base.is_dir(): 
            continue
        for dirpath, _, filenames in os.walk(base):
            for n in filenames:
                if n.lower().endswith(exts):
                    yield Path(dirpath) / n

_LOGO_INDEX: dict[str, str] = {}

def _rebuild_logo_index():
    _LOGO_INDEX.clear()
    # explicit mappings first (python + json)
    for team, path in (LOGOS_RAW or {}).items():
        p = Path(path)
        if not p.is_absolute():
            p = _REPO_ROOT / path
        if p.is_file():
            _LOGO_INDEX[_alnum(team)] = str(p)
    # discovered files
    for path in _iter_logo_files():
        base = path.stem
        for key in {
            _alnum(base),
            re.sub(r"[^a-z0-9]+", "-", _norm(base)).strip("-"),
            _norm(base).replace(" ", "_"),
        }:
            _LOGO_INDEX.setdefault(key, str(path))

_rebuild_logo_index()

def mascot_for(team_name: str) -> Optional[str]:
    if not team_name:
        return None
    return _MASCOTS_BY_NORM.get(_norm(team_name)) or _MASCOTS_BY_ALNUM.get(_alnum(team_name))

def logo_for(team_name: str) -> Optional[str]:
    if not team_name:
        return None
    # explicit first
    p = LOGOS_RAW.get(team_name) or LOGOS_RAW.get(_norm(team_name)) or LOGOS_RAW.get(_alnum(team_name))
    if p:
        pth = Path(p)
        if not pth.is_absolute():
            pth = _REPO_ROOT / p
        return str(pth) if pth.is_file() else None
    # index
    for key in {
        _alnum(team_name),
        re.sub(r"[^a-z0-9]+", "-", _norm(team_name)).strip("-"),
        _norm(team_name).replace(" ", "_"),
    }:
        if key in _LOGO_INDEX:
            return _LOGO_INDEX[key]
    return None
